language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE ponto_inteligente;'
- mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
- mysql -u root -e "GRANT ALL ON ponto_inteligente.* TO 'root'@'localhost';"